### ISSUE TITLE
Standing todo

### ISSUE THREAD

**Issue by cbahlai** [cbahlai/monarch_regime#3]
- [x] cull out redundancy in figure captions
- [x] update README to include file descriptions
- [x]  add panel labels to monarch fig
- [x]  add panel labels to harmonia fig
- [x] apply @ezipkin's edits
- [x] edit down to MEE word limit
- [x] check over reference formatting
- [x] submit to biorXiv
- [x] add biorXive link to README
- [x] submit to MEE
- [x] caption for new figure
